version: 2
project_name: ai-cli
release:
  github:
    owner: ChambersXDU
    name: ai-cli
builds:
  - id: ai-cli
    binary: ai-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    files:
      - LICENSE
      - README.md
changelog:
  use: git
